---
name: Testing

on:
  workflow_call:

jobs:

  FreeBSD:
    runs-on: ubuntu-24.04
    timeout-minutes: 30

    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        include:
          - {salt-version: "3008.2", python-version: "3.12", osrelease: "14.4"}
          - {salt-version: "3008.2", python-version: "3.12", osrelease: "15.1"}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          fetch-depth: 2  # coverage: Issue detecting commit SHA

      - name: Start VM
        uses: vmactions/freebsd-vm@v1
        with:
          release: ${{ matrix.osrelease }}
          usesh: true

      - name: Install dependencies
        shell: freebsd {0}
        run: |
          pkg install -y python3 py312-cryptography py312-sqlite3 py312-maturin py312-markupsafe uv py312-uv nox rust

      - name: Install Test Requirements
        shell: freebsd {0}
        env:
          SALT_REQUIREMENT: salt==${{ matrix.salt-version }}
        run: |
          nox --force-color -e tests-3 --install-only

      - name: Test
        shell: freebsd {0}
        env:
          SALT_REQUIREMENT: salt==${{ matrix.salt-version }}
          SKIP_REQUIREMENTS_INSTALL: true
        run: |
          nox --force-color -e tests-3 -- -vv --instafail tests/
